export interface CivicReport {
  id: string
  category: 'pothole' | 'water_leakage' | 'streetlight' | 'waste_management' | 'other'
  description: string
  severity: 'low' | 'medium' | 'high'
  department: string
  lat: number
  lon: number
  timeAgo: string
  report: string
  status?: 'reported' | 'acknowledged' | 'verified' | 'in_progress' | 'resolved'
  createdAt?: string
  resolutionTimeEstimate?: string
}

export const seedReports: CivicReport[] = [
  {
    id: '1',
    category: 'pothole',
    description: 'There is a massive pothole right at the Jubilee Hills Check Post roundabout. My car tyre burst yesterday because of it. Please fix urgently — this is a main road with heavy traffic!',
    severity: 'high',
    department: 'GHMC Roads Department',
    lat: 17.4326,
    lon: 78.4071,
    timeAgo: '2 hours ago',
    report: 'A large pothole measuring approximately 2ft×1.5ft has formed at the Jubilee Hills Check Post roundabout junction. The damage has caused at least one vehicle tyre blowout. GHMC Roads Department must dispatch a repair crew on emergency basis.',
    status: 'reported',
    createdAt: '2026-06-28T08:00:00Z',
    resolutionTimeEstimate: '3–5 business days',
  },
  {
    id: '2',
    category: 'streetlight',
    description: 'The streetlight on Banjara Hills Road No. 12 near the wine shop has been dead for 3 weeks. It is very dark at night and I am scared to walk home. Please replace the bulb.',
    severity: 'medium',
    department: 'Electrical/Streetlighting',
    lat: 17.4156,
    lon: 78.4347,
    timeAgo: '5 hours ago',
    report: 'A non-functional streetlight on Banjara Hills Road No. 12 has been creating unsafe conditions for pedestrians after dark. The fault has persisted for over three weeks. GHMC Electrical Department should replace the sodium vapour lamp within the standard maintenance SLA.',
    status: 'acknowledged',
    createdAt: '2026-06-27T15:00:00Z',
    resolutionTimeEstimate: '7–10 business days',
  },
  {
    id: '3',
    category: 'water_leakage',
    description: 'Water pipe has burst on Madhapur IT Corridor near Cyber Towers junction. The entire footpath is flooded and water is wasting. HMWSSB please come immediately!',
    severity: 'high',
    department: 'HMWSSB',
    lat: 17.4485,
    lon: 78.3908,
    timeAgo: '1 hour ago',
    report: 'A burst water main on the Madhapur IT Corridor near Cyber Towers Junction is causing extensive waterlogging, blocking pedestrian access and wasting thousands of litres of water. HMWSSB must dispatch a repair crew on an emergency basis.',
    status: 'in_progress',
    createdAt: '2026-06-28T09:30:00Z',
    resolutionTimeEstimate: '24–48 hours',
  },
  {
    id: '4',
    category: 'waste_management',
    description: 'The garbage bin at Kondapur Signal has been overflowing for 4 days. Stray dogs are scattering the waste all over the road. Smell is unbearable. Please send a truck!',
    severity: 'medium',
    department: 'GHMC Sanitation',
    lat: 17.4600,
    lon: 78.3615,
    timeAgo: '3 hours ago',
    report: 'An overflowing community garbage bin at the Kondapur Signal junction has not been cleared in 4 days, causing unhygienic conditions and attracting stray animals. GHMC Sanitation should schedule immediate collection and increased frequency of pickup.',
    status: 'reported',
    createdAt: '2026-06-28T07:00:00Z',
    resolutionTimeEstimate: '1–2 business days',
  },
  {
    id: '5',
    category: 'pothole',
    description: 'Gachibowli Stadium Road near the DLF building has 5–6 potholes in a row. During rain yesterday my scooter slipped. This is causing accidents. Need urgent repair.',
    severity: 'high',
    department: 'GHMC Roads Department',
    lat: 17.4401,
    lon: 78.3489,
    timeAgo: '4 hours ago',
    report: 'Multiple potholes on Gachibowli Stadium Road near DLF Cybercity have created a serious accident hazard for two-wheelers, especially in wet conditions. GHMC Roads Department must prioritize emergency patching of this high-traffic commercial corridor.',
    status: 'reported',
    createdAt: '2026-06-28T06:00:00Z',
    resolutionTimeEstimate: '2–4 business days',
  },
  {
    id: '6',
    category: 'other',
    description: 'The footpath tiles at Hitech City Main Road near the metro station entrance are completely broken. Several elderly people have fallen. Municipality please repair this footpath.',
    severity: 'medium',
    department: 'GHMC Roads Department',
    lat: 17.4474,
    lon: 78.3762,
    timeAgo: '1 day ago',
    report: 'Badly damaged and uneven footpath tiles on Hitech City Main Road near the metro station entrance present a serious trip hazard for commuters, particularly elderly citizens and those with disabilities. GHMC should schedule resurfacing as part of the smart city footpath program.',
    status: 'acknowledged',
    createdAt: '2026-06-27T10:00:00Z',
    resolutionTimeEstimate: '2–3 weeks',
  },
  {
    id: '7',
    category: 'water_leakage',
    description: 'Water leaking from underground pipe near Kukatpally Housing Board bus stop. The road is caving in and I am worried it will collapse. Please check immediately.',
    severity: 'high',
    department: 'HMWSSB',
    lat: 17.4849,
    lon: 78.3985,
    timeAgo: '6 hours ago',
    status: 'in_progress',
    createdAt: '2026-06-28T04:30:00Z',
    report: 'A suspected underground pipe leak near Kukatpally Housing Board bus stop has caused road subsidence. The sinkhole risk is significant given the volume of bus and auto traffic. HMWSSB crew is on site for assessment and emergency repair.',
    resolutionTimeEstimate: '3–7 business days',
  },
  {
    id: '8',
    category: 'streetlight',
    description: 'Four streetlights are completely dark on Lingampally Station Road near the railway crossing. It is pitch black at night and very dangerous for commuters returning from the station.',
    severity: 'low',
    department: 'Electrical/Streetlighting',
    lat: 17.4834,
    lon: 78.3270,
    timeAgo: '8 hours ago',
    status: 'verified',
    createdAt: '2026-06-28T02:00:00Z',
    report: 'Multiple non-functional streetlights on Lingampally Station Road near the railway level crossing have been confirmed by the electrical team. The area experiences high pedestrian volume from late-night trains. Replacement work has been scheduled.',
    resolutionTimeEstimate: '10–14 business days',
  },
  {
    id: '9',
    category: 'waste_management',
    description: 'Someone has dumped construction debris on Miyapur X Roads near the Satyam Theatre. Huge pile of rubble blocking the footpath. Pedestrians are walking on the road and almost getting hit.',
    severity: 'medium',
    department: 'GHMC Sanitation',
    lat: 17.4948,
    lon: 78.3764,
    timeAgo: '3 hours ago',
    status: 'reported',
    createdAt: '2026-06-28T07:30:00Z',
    report: 'Illegally dumped construction waste at Miyapur X Roads near Satyam Theatre is blocking the pedestrian footpath, forcing pedestrians onto the main road and creating accident risk. GHMC Sanitation must arrange debris removal and issue notice to the responsible party.',
    resolutionTimeEstimate: '24–72 hours',
  },
  {
    id: '10',
    category: 'other',
    description: 'The median divider on Film Nagar Road 45 near the director\'s bungalows has collapsed. Two large sections of the concrete divider have fallen into the road. Risk of accident at night.',
    severity: 'low',
    department: 'GHMC Roads Department',
    lat: 17.4187,
    lon: 78.4029,
    timeAgo: '2 days ago',
    status: 'resolved',
    createdAt: '2026-06-26T08:00:00Z',
    report: 'Collapsed median divider sections on Film Nagar Road 45 have been removed and temporary reflective markers placed by GHMC. Permanent repair of the median has been scheduled for the upcoming maintenance cycle.',
    resolutionTimeEstimate: '4–8 hours',
  },
]
